name: Library App CI/CD
run-name: Build, Test, Dockerize & Deploy Library App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # --------------------------
  # 1) Run Unit Tests
  # --------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Run pytest
        run: pytest -v

  # --------------------------
  # 2) Build and Push Docker Image
  # --------------------------
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test   # only runs if tests succeed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t library-app:latest .
          docker tag library-app:latest ${{ secrets.DOCKER_USERNAME }}/library-app:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/library-app:latest

  # --------------------------
  # 3) Deploy (Test Run)
  # --------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-push

    steps:
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/library-app:latest

      - name: Run Docker container
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/library-app:latest > app_output.txt
          cat app_output.txt

      - name: Upload app_output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: library_app_output
          path: app_output.txt
